[package]
name = "pbs_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbs_core = {path = "../pbs_core"}
egui = "0.22.0"
eframe = "0.22.0"